<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PSK9T3U" failures="0" tests="1" name="Runner.NewExcelTestRunner" time="1.062" errors="1" timestamp="2023-03-30T17:15:43 IST" skipped="0">
  <testcase classname="Runner.NewExcelTestRunner" name="test" time="1.062">
    <error message="path must exist: C:\Users\ININDC00073\git\AZENTIO-CSM_Kamalapriya\AzentioAutomationFramework_CSM\src\test\java\features\AccountRestriction.feature" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: path must exist: C:\Users\ININDC00073\git\AZENTIO-CSM_Kamalapriya\AzentioAutomationFramework_CSM\src\test\java\features\AccountRestriction.feature
at io.cucumber.core.resource.PathScanner.findResourcesForPath(PathScanner.java:44)
at io.cucumber.core.resource.PathScanner.findResourcesForUri(PathScanner.java:28)
at io.cucumber.core.resource.ResourceScanner.findResourcesForUri(ResourceScanner.java:61)
at io.cucumber.core.resource.ResourceScanner.scanForResourcesUri(ResourceScanner.java:134)
at io.cucumber.core.runtime.FeaturePathFeatureSupplier.loadFeatures(FeaturePathFeatureSupplier.java:62)
at io.cucumber.core.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:45)
at Runner.CucumberRunTime.run(CucumberRunTime.java:83)
at Runner.CucumberRunner.run(CucumberRunner.java:55)
at Runner.CucumberRunner.run(CucumberRunner.java:25)
at Runner.NewExcelTestRunner.excelTestArea(NewExcelTestRunner.java:34)
at Runner.NewExcelTestRunner.test(NewExcelTestRunner.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test -->
  <system-out/>
</testsuite> <!-- Runner.NewExcelTestRunner -->
