<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PSK9T3U" failures="1" tests="1" name="Runner.TestApplication" time="78.015" errors="0" timestamp="2023-01-24T15:11:46 IST" skipped="0">
  <testcase classname="Runner.TestApplication" name="runScenario" time="78.015">
    <failure message="expected [File extension is not as per the configuration] but found [File validated successfully]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [File extension is not as per the configuration] but found [File validated successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.Bank_Recon.check_the_file_validated_successfully_or_not(Bank_Recon.java:105)
at âœ½.check the file validated  successfully or not(file:///C:/Users/ININDC00071/git/AzentioAutomationFramework_KarthiM/AzentioAutomationFramework_ExcelKUBSKarthiM2/src/test/java/features/BankReconExcel.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.TestApplication -->
